APP_BASE_URL      = 'https://portoapicloud-hml.portoseguro.com.br'
APP_CONTENT_TYPE  = 'application/json'
AUTH_CONTENT_TYPE = 'application/x-www-form-urlencoded'
GRANT_TYPE        = 'client_credentials'
INGRESS_URL       = ''
