APP_BASE_URL      = 'https://portoapicloud-hml.portoseguro.com.br'
APP_CONTENT_TYPE  = 'application/json'
AUTH_CONTENT_TYPE = 'application/x-www-form-urlencoded'
GRANT_TYPE        = 'client_credentials'
INGRESS_URL       = 'https://internal-k8s-meiosdep-ingressm-64700d1053-943128772.ca-central-1.elb.amazonaws.com'
